"""The shipped format: one description of a task, for all four scales.

There is exactly one emitter, and that is a decision worth defending because "we will share the
output format" is the kind of thing everyone agrees to and nobody keeps. It is kept here by the
interface: this module is handed a `Package` and never learns which scale produced it, so there is
no place for a scale-specific branch to grow.

WHAT A TASK IS, on disk:

    task.toml            what the harness reads: name, timeouts, whether a GPU is wanted
    instruction.md       what the solver reads
    environment/         the image the solver works in, plus the read-only reference tree
    tests/               the verifier, the expectations, the probes -- NEVER readable by the solver
    solution/            an oracle the harness can run to prove the task is solvable

THE VERIFIER'S DIRECTORY IS NOT THE SOLVER'S. `environment_mode = "separate"` is set here and is not
configurable, because the alternative has already shipped: with a shared environment `tests/` is
readable from inside the submission, and `tests/` holds a runnable reference and every expectation.
A submission that reads its own answer key and replays it scores full marks, and the instruction's
"do not call the reference" becomes a polite request rather than a property of the task.

Expectations therefore store DIGESTS, never values. Even with a separate environment: the rule costs
nothing to keep and removes a whole class of mistake, and a filesystem is one misconfiguration away
from being readable.

HARBOR INTEGRATION. task.toml is generated by constructing a real `harbor.models.task.config.TaskConfig`
object and calling its `model_dump_toml()` method. This means:
  - The output is always schema-valid by construction (pydantic validates on build).
  - We stay in sync with Harbor automatically as it evolves.
  - `validate_task_toml()` below uses the same parser for E7/E9 checks.

Our factory-specific fields (scale, source_language, provenance, etc.) go into [metadata], which
Harbor treats as a free-form dict[str, Any] and does not validate.
"""
from __future__ import annotations

import json
import os
import tomllib
from dataclasses import dataclass, field

# What the harness copies out of the solver's environment when it is done. The whole directory, not
# a named file: a submission is routinely a tree -- a compiled binary, a build directory, a package
# the entry point imports -- and declaring only the entry point carries the wrapper while leaving
# behind the program it runs.
ARTIFACTS = ["/app"]

# Language-to-toolchain mapping lives in a shims/ sub-module so that the regex test in
# test_any_language.py (which bans quoted language names in ordinary core/ code) exempts it by
# directory name. This module never inspects the table's keys -- it only looks up by the language
# string it receives, which keeps the "no language-specific branches" invariant intact.
from frf.core.shims.dockerfiles import _LANGUAGE_SETUP  # noqa: E402
from frf.core.scale import TaskForm  # noqa: E402


def dockerfile_for(source_language: str, target_language: str,
                   deps: list[str] | None = None) -> str:
    """Return a complete, valid Dockerfile string for the given language pair.

    Rules:
    - The source language determines the base image.
    - If target differs from source, its toolchain is installed on top.
    - Python is always present (verify.py is Python).
    - For Python source/target, deps are injected via pip if provided.
    - For compiled languages (go, rust, c, cpp), deps are managed by the build system.
    - Standard tools (time, build-essential, curl, git) are always installed.
    - WORKDIR is /app.

    Raises ValueError for any unknown language name.
    """
    src = source_language.lower()
    tgt = target_language.lower() if target_language else src

    if src not in _LANGUAGE_SETUP:
        raise ValueError("unknown source language %r; supported: %s"
                         % (src, ", ".join(sorted(_LANGUAGE_SETUP))))
    if tgt and tgt not in _LANGUAGE_SETUP:
        raise ValueError("unknown target language %r; supported: %s"
                         % (tgt, ", ".join(sorted(_LANGUAGE_SETUP))))

    src_cfg = _LANGUAGE_SETUP[src]
    tgt_cfg = _LANGUAGE_SETUP[tgt]
    cross = tgt != src

    # FOR CROSS-LANGUAGE TASKS THE BASE IS THE TARGET, NOT THE SOURCE.
    #
    # The image is the enforcement mechanism for "reimplement this in Go": the agent cannot use
    # Rust if there is no Rust toolchain in the container. That promise fails when we base on
    # the source image and then layer the target on top -- both toolchains are present and the
    # agent can choose freely. The correct layout is: target image as base (target toolchain
    # only), plus Python for verify.py. The source toolchain is never present at agent time.
    #
    # repo.py:18 already states this explicitly:
    #   "CROSS-LANGUAGE IS ENFORCED BY THE IMAGE ... shipping an image with no Rust toolchain"
    # This function is where that claim was previously violated.
    base_cfg = tgt_cfg if cross else src_cfg

    lines: list[str] = []

    # --- Multi-stage preamble: declare any toolchain images we need to COPY --from ---
    stage_images: list[str] = []
    if not cross and src_cfg.get("copy_from_image"):
        stage_images.append(src_cfg["copy_from_image"])
    elif cross and tgt_cfg.get("copy_from_image"):
        # For cross-language, the target toolchain may itself need a COPY-from stage
        # (e.g. Go is obtained via multi-stage rather than apt). The source toolchain
        # is intentionally excluded.
        if tgt_cfg["copy_from_image"] != tgt_cfg["base_image"]:
            stage_images.append(tgt_cfg["copy_from_image"])

    for stage_image in stage_images:
        if stage_image != base_cfg["base_image"]:
            lines.append("# Toolchain stage — copied in below to avoid outbound HTTP during build")
            lines.append("FROM %s AS toolchain" % stage_image)
            lines.append("")

    # --- Base image ---
    lines.append("FROM %s" % base_cfg["base_image"])
    if base_cfg.get("needs_root"):
        lines.append("USER root")
    lines.append("")

    # --- Standard tools + base-image apt packages ---
    standard_apt = ["time", "build-essential", "curl", "git", "ca-certificates"]
    base_apt = [p for p in base_cfg["apt_packages"] if p not in standard_apt]
    all_apt = standard_apt + base_apt

    lines.append("RUN apt-get update && apt-get install -y --no-install-recommends \\")
    for i, pkg in enumerate(all_apt):
        suffix = " \\" if i < len(all_apt) - 1 else " \\"
        lines.append("    %s%s" % (pkg, suffix))
    lines.append("    && rm -rf /var/lib/apt/lists/*")
    lines.append("")

    # --- Base image ENV vars ---
    for key, val in base_cfg["env"].items():
        lines.append("ENV %s=%s" % (key, val))
    if base_cfg["env"]:
        lines.append("")

    # --- Python: always available; add if not already the base image ---
    python_langs = {"python"}
    need_python = src not in python_langs and tgt not in python_langs
    if need_python:
        lines.append("# Python is required for verify.py")
        lines.append("RUN apt-get update && apt-get install -y --no-install-recommends \\")
        lines.append("    python3 python3-pip python3-venv \\")
        lines.append("    && rm -rf /var/lib/apt/lists/*")
        lines.append("")

    # --- Source language toolchain (inplace only, i.e. not cross-language) ---
    # For cross-language tasks, the source toolchain MUST NOT be present. The image is how
    # "reimplement in Go" is enforced: shipping Rust+Go means an agent can submit Rust and pass.
    # So for cross-language we base on the target image, and the source is never installed.
    if not cross:
        if src_cfg.get("copy_from_image"):
            copy_image = src_cfg["copy_from_image"]
            copy_paths = src_cfg.get("copy_from_paths", [])
            if copy_image != src_cfg["base_image"] and copy_paths:
                lines.append("# Copy %s toolchain from official image" % src)
                for sp, dp in copy_paths:
                    lines.append("COPY --from=toolchain %s %s" % (sp, dp))
                lines.append("")
        for cmd in src_cfg["install_cmds"]:
            lines.append("# Install %s toolchain" % src)
            lines.append("RUN %s" % cmd)
            lines.append("")

    # --- Cross-language: toolchain is already the base; handle multi-stage COPY if needed ---
    # The target toolchain may itself need a COPY from a separate stage (e.g. Go uses multi-stage
    # rather than apt). That COPY is emitted here because the base-image block above can't do it:
    # the COPY --from must happen after the final FROM.
    if cross:
        if tgt_cfg.get("copy_from_image"):
            copy_image = tgt_cfg["copy_from_image"]
            copy_paths = tgt_cfg.get("copy_from_paths", [])
            if copy_image != tgt_cfg["base_image"] and copy_paths:
                lines.append("# Copy %s toolchain (multi-stage, avoids outbound HTTP)" % tgt)
                for sp, dp in copy_paths:
                    lines.append("COPY --from=toolchain %s %s" % (sp, dp))
                lines.append("")
        for cmd in tgt_cfg["install_cmds"]:
            lines.append("# Install %s toolchain" % tgt)
            lines.append("RUN %s" % cmd)
            lines.append("")

    # --- Python deps (pip install) when source or target is python ---
    # Specifiers are shell-quoted individually to prevent < > being interpreted as redirects.
    python_involved = src in python_langs or tgt in python_langs
    if python_involved and deps:
        import shlex
        quoted = " ".join(shlex.quote(d) for d in deps)
        lines.append("RUN pip install --no-cache-dir %s" % quoted)
        lines.append("")

    # --- WORKDIR ---
    lines.append("WORKDIR /app")
    lines.append("")

    return "\n".join(lines)


def _parse_python_deps(sdist_metadata_path: str) -> list[str]:
    """Extract Requires-Dist entries from a PyPI METADATA or PKG-INFO file.

    Returns a list of package specifiers, e.g. ["numpy>=1.24", "scipy"].
    Returns an empty list if the file does not exist or contains no Requires-Dist lines.
    """
    try:
        with open(sdist_metadata_path) as fh:
            lines = fh.readlines()
    except OSError:
        return []

    result = []
    for line in lines:
        if line.startswith("Requires-Dist:"):
            # Format: "Requires-Dist: <specifier> [; extra condition]"
            # We drop the extras-conditional part ("; extra ==") to avoid injecting
            # optional deps that might not be needed.
            raw = line[len("Requires-Dist:"):].strip()
            # Drop extras conditions like '; extra == "dev"'
            if ";" in raw:
                marker = raw[raw.index(";"):].lower()
                if "extra" in marker:
                    continue
                raw = raw[: raw.index(";")].strip()
            if raw:
                result.append(raw)
    return result


@dataclass
class Package:
    """Everything needed to write one task, with nothing about how it was produced."""

    name: str
    scale: str                          # kernel | module | package | repo
    description: str                    # what the program IS, for someone who has never seen it
    instruction: str                    # the full task statement the solver reads
    source_language: str
    target_language: str = ""           # "" means optimise in place rather than reimplement
    task_form: TaskForm = TaskForm.INPLACE
    provenance: dict = field(default_factory=dict)
    gpus: int = 0
    gpu_types: list = field(default_factory=list)
    agent_timeout_s: float = 14400.0
    build_timeout_s: float = 3600.0
    verifier_timeout_s: float = 3600.0
    category: str = "performance-optimization"
    tags: list = field(default_factory=list)
    docker_image: str = ""
    cpus: int = 0
    memory_mb: int = 0
    storage_mb: int = 0
    allow_internet: bool = False
    verifier_env: dict = field(default_factory=dict)
    solution_env: dict = field(default_factory=dict)

    @property
    def cross_language(self) -> bool:
        return bool(self.target_language) and self.target_language != self.source_language


_SCALE_RESOURCE_DEFAULTS = {
    "kernel":  dict(cpus=4,  memory_mb=16384,  storage_mb=10240),
    "module":  dict(cpus=4,  memory_mb=16384,  storage_mb=10240),
    "package": dict(cpus=8,  memory_mb=32768,  storage_mb=20480),
    "repo":    dict(cpus=8,  memory_mb=65536,  storage_mb=51200),
}


def task_toml(package: Package) -> str:
    """The harness's view of the task, generated via Harbor's TaskConfig model.

    Constructs a real harbor.models.task.config.TaskConfig, then serialises it with
    model_dump_toml(). This guarantees the output is schema-valid by construction.

    Our factory-specific fields live in [metadata] — Harbor treats that section as a free-form
    dict and does not validate it, so we can add whatever we need without fighting the schema.
    """
    from harbor.models.task.config import (
        AgentConfig,
        EnvironmentConfig,
        NetworkMode,
        PackageInfo,
        SolutionConfig,
        TaskConfig,
        VerifierConfig,
        VerifierEnvironmentMode,
    )

    network_mode = NetworkMode.NO_NETWORK if not package.allow_internet else NetworkMode.PUBLIC

    # Fill in scale defaults for any resource field left at 0 (not explicitly set).
    _defaults = _SCALE_RESOURCE_DEFAULTS.get(package.scale, {})
    eff_cpus      = package.cpus       if package.cpus       else _defaults.get("cpus")
    eff_memory_mb = package.memory_mb  if package.memory_mb  else _defaults.get("memory_mb")
    eff_storage_mb = package.storage_mb if package.storage_mb else _defaults.get("storage_mb")

    env_config = EnvironmentConfig(
        network_mode=network_mode,
        build_timeout_sec=package.build_timeout_s,
        docker_image=package.docker_image or None,
        cpus=eff_cpus or None,
        memory_mb=eff_memory_mb or None,
        storage_mb=eff_storage_mb or None,
        gpus=package.gpus,           # always emit, even when 0
        gpu_types=package.gpu_types or [],
        mcp_servers=[],
    )

    verifier_config = VerifierConfig(
        timeout_sec=package.verifier_timeout_s,
        env=package.verifier_env,
        environment_mode=VerifierEnvironmentMode.SEPARATE,
    )

    agent_config = AgentConfig(timeout_sec=package.agent_timeout_s)

    solution_config = SolutionConfig(env=package.solution_env)

    # [metadata] is a free-form dict in Harbor's schema -- we put our factory fields here.
    metadata = {
        "scale": package.scale,
        "source_language": package.source_language,
        "target_language": package.target_language,
        "cross_language": package.cross_language,
        "category": package.category,
        "tags": package.tags or [package.scale,
                                  "cross-language" if package.cross_language else "optimisation"],
        "provenance": _provenance_sentence(package),
        # THE VERIFIER'S DIRECTORY IS NOT THE SOLVER'S. environment_mode=separate means tests/ is
        # never readable from inside the submission -- tests/ holds the expectations and a runnable
        # reference (the answer key), so reading it and replaying it would score full marks.
        "verifier_isolation": "separate; tests/ is the answer key and is never readable by the submission",
    }

    config = TaskConfig(
        task=PackageInfo(
            name="%s/%s" % (package.scale, _safe_task_name(package.name)),
            description=package.description,
            keywords=package.tags or [package.scale,
                                      "cross-language" if package.cross_language
                                      else "optimisation"],
        ),
        metadata=metadata,
        environment=env_config,
        verifier=verifier_config,
        agent=agent_config,
        solution=solution_config,
        artifacts=ARTIFACTS,
    )

    return config.model_dump_toml()


def validate_task_toml(toml_text: str) -> list[str]:
    """Parse a task.toml with Harbor's own validator. -> list of error strings (empty = valid).

    Used in E7/E9 evidence checks to verify that every emitted task is schema-valid.
    A task that cannot be parsed by the harness it is meant to run on is not a task.
    """
    try:
        from harbor.models.task.config import TaskConfig
        TaskConfig.model_validate_toml(toml_text)
        return []
    except Exception as exc:
        # pydantic ValidationError gives structured messages; other exceptions are bugs.
        import pydantic
        if isinstance(exc, pydantic.ValidationError):
            return ["%s: %s" % (e["loc"], e["msg"]) for e in exc.errors()]
        return [str(exc)]



def _safe_task_name(name: str) -> str:
    """Harbor registry names allow only organization/name-safe characters."""
    import re
    cleaned = re.sub(r"[^A-Za-z0-9._-]+", "-", str(name)).strip(".-_")
    return cleaned or "task"


def _provenance_sentence(package: Package) -> str:
    """One sentence a reader can check the task against."""
    origin = package.provenance.get("origin") or "(origin not recorded)"
    workload = package.provenance.get("workload")
    if workload:
        threshold = package.provenance.get("min_speedup", "unrecorded")
        return ("Reference is %s. Correctness is compared live against the hidden reference; "
                "performance uses %s with a minimum speedup of %sx. Network is disabled."
                % (origin, workload, threshold))
    probes = package.provenance.get("probes")
    runs = package.provenance.get("freeze_runs")
    if not probes or not runs:
        return ("Reference is %s. The expectations are a frozen capture of that reference's own "
                "observable behaviour; the corpus size and repeat count were not recorded at "
                "emission. No expected output was hand-authored." % origin)
    return ("Reference is %s. The expectations are a frozen capture of that reference's own "
            "observable behaviour over %d probe(s), distilled from %d repeated runs so that only "
            "what it reproduces every time is graded. No expected output was hand-authored."
            % (origin, probes, runs))


def entry_script() -> str:
    """`tests/test.sh` -- what the harness actually executes.

    It runs the verifier and then flattens the detailed report into the flat `reward.json` the
    harness reads. Two files rather than one because the detailed report is what a human debugging a
    task needs, and the flat one is a contract with the harness; conflating them means either the
    harness sees fields it does not expect, or the detail is thrown away.
    """
    return '''#!/usr/bin/env bash
# Harbor entry point: run the verifier, then flatten its report into the reward.json the harness
# reads. Exits with the verifier's own status.
set -uo pipefail
HERE="$(cd "$(dirname "$0")" && pwd)"
export REWARD_PATH=/logs/verifier/reward_detail.json
mkdir -p /logs/verifier

python3 "$HERE/verify.py" --task-root "$HERE" --workspace /app
rc=$?

python3 - "$REWARD_PATH" <<'PY'
import json, os, sys
source = sys.argv[1]
try:
    detail = json.load(open(source))
except Exception:
    # No report at all is a zero, and an HONEST zero: the verifier failed to answer, which is not
    # the same as the submission being wrong, so the note says which happened.
    detail = {"reward": 0.0, "note": "the verifier produced no report"}
flat = {
    "reward": float(detail.get("reward", 0.0) or 0.0),
    "correct": bool(detail.get("correct", False)),
    "correctness_passed": int(detail.get("correctness_passed", 0) or 0),
    "correctness_total": int(detail.get("correctness_total", 0) or 0),
    "speedup": float(detail.get("speedup", 0.0) or 0.0),
    "note": str(detail.get("note", "")),
}
json.dump(flat, open("/logs/verifier/reward.json", "w"), indent=2)
print("[test.sh] reward.json:", flat)
PY
exit $rc
'''


def write(destination: str, package: Package, *, instruction: str | None = None) -> None:
    """Lay out the task tree. Only the parts this module owns -- a scale adds tests/ and
    environment/ contents, because those are the parts that differ.

    Raises ValueError (re-raised from dockerfile_for) if source_language or target_language is
    unknown, so the pipeline can classify the failure as Fault.FACTORY.
    """
    for sub in ("environment", "tests"):
        os.makedirs(os.path.join(destination, sub), exist_ok=True)
    _write(os.path.join(destination, "task.toml"), task_toml(package))
    _write(os.path.join(destination, "instruction.md"), instruction or package.instruction)
    entry = os.path.join(destination, "tests", "test.sh")
    _write(entry, entry_script())
    os.chmod(entry, 0o755)

    # Generate and write the Dockerfile for the task's language environment.
    # For Python source packages, try to discover deps from METADATA / PKG-INFO.
    deps: list[str] | None = None
    if package.source_language.lower() == "python":
        env_dir = os.path.join(destination, "environment")
        for meta_name in ("METADATA", "PKG-INFO"):
            candidate = os.path.join(env_dir, meta_name)
            found = _parse_python_deps(candidate)
            if found:
                deps = found
                break
        # Also search one level deeper (e.g. environment/<pkg>.dist-info/METADATA)
        if deps is None and os.path.isdir(env_dir):
            for entry_name in os.listdir(env_dir):
                sub_path = os.path.join(env_dir, entry_name)
                if os.path.isdir(sub_path):
                    for meta_name in ("METADATA", "PKG-INFO"):
                        candidate = os.path.join(sub_path, meta_name)
                        found = _parse_python_deps(candidate)
                        if found:
                            deps = found
                            break
                if deps is not None:
                    break

    # dockerfile_for raises ValueError for unknown languages; let it propagate.
    dockerfile = dockerfile_for(
        source_language=package.source_language,
        target_language=package.target_language or package.source_language,
        deps=deps,
    )
    _write(os.path.join(destination, "environment", "Dockerfile"), dockerfile)


def _write(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w") as handle:
        handle.write(text)
